[2023-05-02 00:41:10,173] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.44:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:15,935] ERROR _log() L224  192.168.0.44 - - [02/May/2023 00:41:15] code 400, message Bad request version ('\x00\x02\x01\x00\x00#\x00\x00\x00') - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:15,950] ERROR _log() L224  192.168.0.44 - - [02/May/2023 00:41:15] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x9aßì+\x1b\\(¬') - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:17,308] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:17] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:17,317] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:17] "[32mGET /openapi HTTP/1.1[0m" 308 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:17,327] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:17] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:17,422] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:17] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:17,442] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:17] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:17,449] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:17] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:17,452] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:17] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:17,539] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:17] "GET /openapi/static/images/apidoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:26,861] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:26] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:26,884] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:26] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:26,901] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:26] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:26,905] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:26] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:27,004] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:27] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:27,056] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:27] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:27,071] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:27] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:41:59,694] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:41:59] "GET /carros HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:42:36,810] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:42:36] "POST /carro HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:42:53,023] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:42:53] "GET /carros HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:43:17,918] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:43:17] "DELETE /carro?id=2 HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:43:31,725] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:43:31] "GET /carros HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:43:57,492] WARNING get_carro() L101  Erro ao buscar o carro com o ID: '1', Carro não encontrado na base :/ - call_trace=G:\Repositorios\MVP -- PUC\back-end\app.py L101 
[2023-05-02 00:43:57,493] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:43:57] "[33mGET /carro?placa=LKJ-8910 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:44:05,165] WARNING get_carro() L101  Erro ao buscar o carro com o ID: '1', Carro não encontrado na base :/ - call_trace=G:\Repositorios\MVP -- PUC\back-end\app.py L101 
[2023-05-02 00:44:05,169] INFO _log() L224  192.168.0.44 - - [02/May/2023 00:44:05] "[33mGET /carro?placa=LKJ- HTTP/1.1[0m" 404 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:44:24,291] INFO _log() L224  127.0.0.1 - - [02/May/2023 00:44:24] "GET /carros HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:44:38,081] INFO _log() L224  127.0.0.1 - - [02/May/2023 00:44:38] "OPTIONS /carro?id=4 HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:44:38,173] INFO _log() L224  127.0.0.1 - - [02/May/2023 00:44:38] "DELETE /carro?id=4 HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:45:04,199] INFO _log() L224  127.0.0.1 - - [02/May/2023 00:45:04] "POST /carro HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
[2023-05-02 00:45:05,930] INFO _log() L224  127.0.0.1 - - [02/May/2023 00:45:05] "GET /carros HTTP/1.1" 200 - - call_trace=C:\Users\Tiago França\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\_internal.py L224 
